# Generated by Django 5.0.1 on 2024-02-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('pet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('birth_date', models.DateField(max_length=99)),
                ('gender', models.BooleanField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.client')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_history',
            fields=[
                ('Medical_history_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.pets')),
            ],
        ),
    ]
