# Generated by Django 5.0.1 on 2024-02-20 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_log_in_remove_client_email_appointment_client_log_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hello.pets'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log_in',
            name='log_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
