# Generated by Django 5.0.1 on 2024-02-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_remove_appointment_client_id_appointment_pet_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
    ]
