# Generated by Django 5.0.1 on 2024-02-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_remove_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='name',
            field=models.CharField(default='Juan', max_length=100),
            preserve_default=False,
        ),
    ]
