# Generated by Django 5.0.1 on 2024-02-20 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_pets_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical/file/')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.report')),
            ],
        ),
    ]
