# Generated by Django 5.0.1 on 2024-02-21 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='appointement_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.appointment'),
        ),
    ]
