# Generated by Django 5.0.1 on 2024-02-21 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_alter_report_appointement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='appointement_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hello.appointment'),
            preserve_default=False,
        ),
    ]
