# Generated by Django 5.0.1 on 2024-02-28 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_alter_report_appointement_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('vaccine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='update_note',
            field=models.CharField(default='smth', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('vaccination_id', models.IntegerField(primary_key=True, serialize=False)),
                ('medical_history_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.medical_history')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.vaccines')),
            ],
        ),
    ]
