# Generated by Django 5.0.1 on 2024-02-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_vaccines_report_update_note_vaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_created',
            field=models.DateField(auto_now_add=True, default='2023-04-27'),
            preserve_default=False,
        ),
    ]
