# Generated by Django 5.0.1 on 2024-03-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_report_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='allergies',
            field=models.CharField(default='Something1, Something2, Something3', max_length=100),
            preserve_default=False,
        ),
    ]
