# Generated by Django 5.0.1 on 2024-03-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_in',
            name='key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pets',
            name='tipo_sangre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
