# Generated by Django 5.0.1 on 2024-05-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_in',
            name='password',
        ),
        migrations.RemoveField(
            model_name='log_in',
            name='user_name',
        ),
    ]
