# Generated by Django 5.0.1 on 2024-03-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0002_log_in_key_pets_tipo_sangre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone_owner',
            name='country_intials',
        ),
        migrations.RemoveField(
            model_name='vet',
            name='country_intials',
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(default=500004, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vet',
            name='postal_code',
            field=models.CharField(default=10000000, max_length=100),
            preserve_default=False,
        ),
    ]
