# Generated by Django 5.0.1 on 2024-03-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0002_pets_image_vaccination_vaccine_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='image',
            field=models.ImageField(upload_to='pet/images/'),
        ),
    ]
