# Generated by Django 5.0.1 on 2024-03-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0003_alter_pets_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default=1, upload_to='client/images/'),
            preserve_default=False,
        ),
    ]
