# Generated by Django 5.0.1 on 2024-03-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0003_remove_phone_owner_country_intials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='average_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
