# Generated by Django 5.0.1 on 2024-03-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0004_client_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='image',
            field=models.ImageField(null=True, upload_to='user/images/'),
        ),
    ]
