# Generated by Django 5.0.1 on 2024-03-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0004_vet_average_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
