# Generated by Django 5.0.1 on 2024-04-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0005_appointment_appointment_accepted_vet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_in',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
