# Generated by Django 5.0.1 on 2024-03-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0005_alter_appointment_appointment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='comment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='image',
            field=models.ImageField(null=True, upload_to='user/images/'),
        ),
    ]
