# Generated by Django 5.0.1 on 2024-03-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_User', '0005_alter_appointment_appointment_id_and_more'),
        ('Client_User', '0006_appointment_comment_appointment_rating'),
    ]

    operations = [
    ]
